import { describe, it, expect, beforeEach } from 'vitest';
import { runCLI, resetDatabase, getCollectionData } from '../../utils';
import path from 'path';

describe('Relation Test: Multi-collection Upsert', () => {
  beforeEach(() => resetDatabase());

  it('should successfully resolve relational payload fields by mapping author email to internal users ID', () => {
    // 1. Create User via UPSERT
    const userConfig = path.resolve(__dirname, '../success-mapping-upsert/config.ts');
    const userData = path.resolve(__dirname, '../success-mapping-upsert/data.jsonl');
    runCLI(`-c ${userConfig} users upsert ${userData}`);

    // 2. Create Post referencing the User strictly by email string
    const postConfig = path.resolve(__dirname, 'config.ts');
    const postData = path.resolve(__dirname, 'data.jsonl');
    const out = runCLI(`-c ${postConfig} posts upsert ${postData}`);

    expect(out).toContain('Operation successful');

    // 3. Assert Post inherently contains the precise user object reference generated by Payload
    const users = getCollectionData('users');
    const posts = getCollectionData('posts');
    const alice = users.find((u: any) => u.email === 'alice@example.com');

    expect(posts).toHaveLength(1);
    expect(posts[0].author.id).toBe(alice.id); // This rigorously tests ID resolution translation!
  }, 30000);
});
